[package]
name = "dynamic_pathfinding"
version = "0.1.0"
edition = "2021"

[dependencies]
pathfinding = "4.0.0"
rand = "0.8.5"
clap = { version = "4.0.29", features = ["derive"] }
rustc-hash = "2.1.1"
